### PR TITLE
FE: Fix refetching data on window focus

### LINKED ISSUE #348: FE: Do not refetch data on window focus
Some components like `ui/clusters/local/schemas/test/edit` does refetch data via tsquery on window focus.
This is considered a harmful behavior, because if there are any unsaved changes made to the schema itself the data will be refetched and the changes would be lost.

TODO:
1. Check all the places where window focus refetch is on but shouldn't be
2. Add `QUERY_REFETCH_OFF_OPTIONS` in these places

### PR DESCRIPTION
**Pull request by masonwoodford**
- [ ] **Breaking change?** (if so, please describe the impact and migration path for existing application instances)

**What changes did you make?** (Give an overview)

Closes #348
I created a new constant QUERY_REFETCH_ON_WINDOW_FOCUS_OFF_OPTION that just has refetchOnWindowFocus false rather than

export const QUERY_REFETCH_OFF_OPTIONS = {
refetchOnMount: false,
refetchOnWindowFocus: false,
refetchIntervalInBackground: false,
};

I created this new constant because when all 3 options are provided, even when the Edit field is updated the UI will not reflect the changes until the page is refreshed. I added this constant to the two Edit components that fetch and place into editable fields.

**Is there anything you'd like reviewers to focus on?**

**How Has This Been Tested?** (put an "x" (case-sensitive!) next to an item)

- [x] No need to
- [x] Manually (please, describe, if necessary)
- [x] Unit checks
- [x] Integration checks
- [x] Covered by existing automation

**Checklist** (put an "x" (case-sensitive!) next to all the items, otherwise the build will fail)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (e.g. **ENVIRONMENT VARIABLES**)
- [x] My changes generate no new warnings (e.g. Sonar is happy)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

Check out [Contributing](https://github.com/kafbat/kafka-ui/blob/main/.github/CONTRIBUTING.md) and [Code of Conduct](https://github.com/kafbat/kafka-ui/blob/main/.github/CODE-OF-CONDUCT.md)

**A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

File: frontend/src/lib/constants.ts [hunk 1]
```diff
@@ -73,6 +73,10 @@ export const QUERY_REFETCH_OFF_OPTIONS = {
   refetchIntervalInBackground: false,
 };
 
+export const QUERY_REFETCH_ON_WINDOW_FOCUS_OFF_OPTION = {
+  refetchOnWindowFocus: false,
```
Comment (Haarolean) [inline frontend/src/lib/constants.ts:77]: I guess we'd need `refetchIntervalInBackground: false` here as well

File: frontend/src/lib/hooks/api/topics.ts [hunk 2]
```diff
@@ -50,10 +51,18 @@ export function useTopics(props: GetTopicsRequest) {
   );
 }
 export function useTopicDetails(props: GetTopicDetailsRequest) {
-  return useQuery(topicKeys.details(props), () => api.getTopicDetails(props));
+  return useQuery(
+    topicKeys.details(props),
+    () => api.getTopicDetails(props),
+    QUERY_REFETCH_ON_WINDOW_FOCUS_OFF_OPTION
```
Comment (Haarolean) [inline frontend/src/lib/hooks/api/topics.ts:57]: the hooks themselves might be used in multiple different places. I don't see a problem with refetching the defails when e.g. viewing topic details (which is okay since you can't edit anything in there), but this should have a differen behavior in topic *edit* view, can we adjust it like that?

**Review by Haarolean — CHANGES_REQUESTED** [review]

**Comment by masonwoodford** [comment]
Have updated with the requested changes by passing a parameter to the query functions. I did want to point out that even though the Edit topic component fetches on window focus I don't see it having the issue that Schemas has, but for consistency I added it there but can remove it as well. It also removes unnecessary api requests.

**Comment by masonwoodford** [comment]
Sorry about that didn't mean to re request review didn't see you had requested another review.

File: frontend/src/lib/constants.ts [hunk 3]
```diff
@@ -73,6 +73,11 @@ export const QUERY_REFETCH_OFF_OPTIONS = {
   refetchIntervalInBackground: false,
 };
 
+export const QUERY_REFETCH_LIMITED_OPTIONS = {
```
Comment (Mgrdich) [inline frontend/src/lib/constants.ts:76]: if we are going to apply the refetch of all queries on window focus , it is better to provide the parameter and the config to the root `QueryClient` that gets pass to the provider rather than passing it as an option to all the queries.

FYI @Haarolean

Comment (masonwoodford) [reply frontend/src/lib/constants.ts:76]: Currently it is not being passed to all queries just ones that are editable so that the fetching does not overwrite any temporary changes made. Should this be provided to all queries instead?

Comment (Haarolean) [reply frontend/src/lib/constants.ts:76]: Nope, as we discussed, only for the views which support editable parts: [source](https://github.com/kafbat/kafka-ui/issues/348#issuecomment-2094976884)

cc @Mgrdich

**Review by Mgrdich — APPROVED** [review]

**Comment by Haarolean** [comment]
@masonwoodford thank you and sorry for the delay!
